import Link from "next/link";

const sections = [
  ["Study support, not a school", "StudyEzy is an educational support tool. It does not replace a qualified teacher, school curriculum, professional advice, or adult supervision. Parents remain responsible for deciding whether an explanation or answer is suitable."],
  ["Accounts and children", "An adult must create and manage the family account. Keep sign-in details private. Parents are responsible for activity performed through their account and for helping children use the service safely."],
  ["AI-generated answers", "Some explanations, translations, feedback, and speech may be generated by third-party AI services. We ground lessons in available curriculum content, but AI can make mistakes. Check important work against the textbook or teacher."],
  ["Textbook pages and uploads", "Only upload material you are permitted to use. StudyEzy may process uploaded pages to organise lessons and examples. Do not upload private information about another person."],
  ["Availability and changes", "We may improve, pause, or change features while the service develops. Pilot access, future plans, and any payment requirement will be shown clearly before a paid change."],
  ["Acceptable use", "Do not misuse the service, access another family’s data, automate abusive traffic, upload harmful material, or use StudyEzy to make high-stakes decisions about a child."],
];

export default function TermsPage() {
  return <LegalPage title="Terms & conditions" intro="These plain-language terms explain how families may use StudyEzy." sections={sections} />;
}

function LegalPage({ title, intro, sections }: { title: string; intro: string; sections: string[][] }) {
  return <main className="mx-auto min-h-screen max-w-3xl py-4"><Link href="/" className="text-sm font-bold text-brand-ink hover:underline">← Back to StudyEzy</Link><article className="mt-10 rounded-3xl border border-slate-200 bg-white p-6 shadow-soft sm:p-10"><h1 className="font-display text-4xl font-bold text-slate-900">{title}</h1><p className="mt-3 leading-7 text-slate-600">{intro}</p><p className="mt-2 text-xs text-slate-400">Last updated: September 2026</p><div className="mt-10 grid gap-7">{sections.map(([heading, body]) => <section key={heading}><h2 className="text-lg font-bold text-slate-900">{heading}</h2><p className="mt-2 leading-7 text-slate-600">{body}</p></section>)}</div></article></main>;
}
