import type { RichScene } from "@/lib/richScene";
import math10_1 from "@/lib/richScenes/cambridge-4-math-10/10.1.json";
import math10_2 from "@/lib/richScenes/cambridge-4-math-10/10.2.json";

/**
 * Model-authored scenes, keyed "<unitKey>/<conceptId>". Generated by
 * scripts/generate-rich-scene.ts and committed as reviewed JSON - see
 * lib/richScene.ts for why the artwork lives in data rather than in code.
 *
 * These take precedence over the hand-coded spec scenes for the same concept,
 * so a concept can be upgraded one at a time without touching its existing
 * scenes.
 */
export const RICH_SCENES: Record<string, RichScene> = {
  "cambridge-4-math-10/10.1": math10_1 as RichScene,
  "cambridge-4-math-10/10.2": math10_2 as RichScene,
};

export function getRichScene(unitKey: string | undefined, conceptId: string): RichScene | undefined {
  if (!unitKey) return undefined;
  return RICH_SCENES[`${unitKey}/${conceptId}`];
}
