import { NextRequest, NextResponse } from "next/server";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { getCurrentUser } from "@/lib/session";
import { UPLOADS_DIR } from "@/lib/uploads";

export const runtime = "nodejs";

const CROPS_DIR = path.join(UPLOADS_DIR, "content-crops");

// Serves images generated by lib/pdfCrop.ts (a real region cropped from a
// unit's source PDF, for a content-pack question whose original diagram
// couldn't be redrawn declaratively) - deliberately separate from
// /api/uploads/[...path], which requires a matching UnitResource/UploadedPage
// row: a generated crop has no such row (it isn't something a family
// uploaded or an admin approved, it's a deterministic byproduct of
// conversion), so that route would 404 it. Still auth-gated the same way -
// this is still real textbook content, not public.
export async function GET(_req: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: "Not signed in." }, { status: 401 });
  }

  const { path: segments } = await params;
  // Reject any segment that could escape CROPS_DIR - these paths are always
  // server-generated (packId/questionId.png), never user input, but a route
  // param is still attacker-reachable input in principle.
  if (segments.some((s) => s.includes("..") || s.includes("/") || s.includes("\\"))) {
    return NextResponse.json({ error: "Invalid path." }, { status: 400 });
  }

  const filePath = path.join(CROPS_DIR, ...segments);
  try {
    const bytes = await readFile(filePath);
    return new NextResponse(new Uint8Array(bytes), {
      headers: { "Content-Type": "image/png", "Cache-Control": "private, max-age=86400" },
    });
  } catch {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }
}
