import { NextRequest, NextResponse } from "next/server";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { getCurrentUser } from "@/lib/session";
import { UPLOADS_DIR } from "@/lib/uploads";

export const runtime = "nodejs";

const ILLUSTRATIONS_DIR = path.join(UPLOADS_DIR, "concept-illustrations");

// Serves images generated by lib/conceptIllustration.ts - same shape as
// /api/content-crops/[...path]/route.ts (a generated file with no matching
// UnitResource/UploadedPage row to gate through /api/uploads instead).
export async function GET(_req: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: "Not signed in." }, { status: 401 });
  }

  const { path: segments } = await params;
  if (segments.some((s) => s.includes("..") || s.includes("/") || s.includes("\\"))) {
    return NextResponse.json({ error: "Invalid path." }, { status: 400 });
  }

  const filePath = path.join(ILLUSTRATIONS_DIR, ...segments);
  try {
    const bytes = await readFile(filePath);
    return new NextResponse(new Uint8Array(bytes), {
      headers: { "Content-Type": "image/png", "Cache-Control": "private, max-age=86400" },
    });
  } catch {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }
}
